[build]
  publish = "dashboard"
  functions = "netlify/functions"
  ignore = "git log -1 --pretty=%B | grep -q '\\[skip ci\\]'"

[build.environment]
  NODE_VERSION = "20"

[dev]
  port = 3001
  functionsPort = 3002
